import { ReservationStatus } from "../models/reservation.model";

export const API_BASE_URL = 'http://localhost:8080';

export const API_ENDPOINTS = {
    apartments: `${API_BASE_URL}/api/apartments`,
    adminApartments: `${API_BASE_URL}/api/admin/apartments`,
    availability: `${API_BASE_URL}/api/availability`,
    reservations: `${API_BASE_URL}/api/reservations`,
    payments: `${API_BASE_URL}/api/payments`,
    auth: {
        register: `${API_BASE_URL}/api/auth/register`,
        login: `${API_BASE_URL}/api/auth/login`,
        forgotPassword: `${API_BASE_URL}/api/auth/forgot-password`,
        resetPassword: `${API_BASE_URL}/api/auth/reset-password`,
    },
    users: {
        me: `${API_BASE_URL}/api/users/me`,
        updateProfile: `${API_BASE_URL}/api/users/me/profile`,
        changePassword: `${API_BASE_URL}/api/users/me/password`,
    },
} as const;

export const DEFAULT_APARTMENT_ID = 1;

export const TOKEN_STORAGE_KEY = 'auth_token';

export const TURNSTILE_SITE_KEY = '0x4AAAAAAEdydktyje4kLdXd'; // if you want it to work on test mode change on 1x00000000000000000000AA

export interface StatusInfo {
    label: string;
    badgeClass: string;
}

export const RESERVATION_STATUS_INFO: Record<ReservationStatus, StatusInfo> = {
    PENDING_PAYMENT: { label: 'Oczekuje płatności', badgeClass: 'badge--pending' },
    CONFIRMED: { label: 'Potwierdzona', badgeClass: 'badge--confirmed' },
    CANCELLED: { label: 'Anulowana', badgeClass: 'badge--cancelled' },
    COMPLETED: { label: 'Zakończona', badgeClass: 'badge--completed' }
};

export const UI_TEXT = {
    navbar: {
        logo: 'Residenza Aurea',
        booking: 'Rezerwacja',
        myReservations: 'Moje rezerwacje',
        adminPanel: 'Panel admina',
        login: 'Zaloguj się',
        register: 'Zarejestruj się',
        logout: 'Wyloguj',
        changeDetails: 'Zmień dane',
        changePassword: 'Zmień hasło',
    },

    home: {
        loading: 'Ładowanie...',
        loadError: 'Nie udało się załadować informacji o apartamencie.',
        eyebrowPrefix: 'Prywatny wynajem · ',
        pricePerNight: 'PLN / noc',
        maxGuestsPrefix: 'Maks. ',
        maxGuestsSuffix: ' gości',
        areaSuffix: ' m²',
        floorSuffix: '. piętro',
        cta: 'Zarezerwuj teraz',

        gallery: {
            eyebrow: 'GALERIA',
            title: 'Przestrzeń, która zapada w pamięć',
            checkAvailability: 'SPRAWDŹ DOSTĘPNOŚĆ',
        },
    },

    booking: {
        sectionDates: 'Wybierz daty pobytu',
        title: 'Rezerwacja',
        loadingCalendar: 'Ładowanie kalendarza...',
        legendSelected: 'Wybrana data',
        legendTaken: 'Zajęte',
        guestsLabel: 'Liczba gości',
        maxGuestsPrefix: 'Maks. ',
        maxGuestsSuffix: ' osoby',
        summaryTitle: 'Podsumowanie',
        checkIn: 'Zameldowanie',
        checkOut: 'Wymeldowanie',
        guests: 'Goście',
        total: 'Łącznie',
        placeholder: 'Wybierz daty, aby zobaczyć cenę',
        guestCardTitle: 'Dane gościa',
        nameLabel: 'Imię i nazwisko',
        namePlaceholder: 'Jan Kowalski',
        emailLabel: 'Adres e-mail',
        emailPlaceholder: 'jan@example.com',
        phoneLabel: 'Numer telefonu',
        phonePlaceholder: '+48 600 000 000',
        submitIdle: 'Rezerwuj',
        submitBusy: 'Wysyłanie...',
        currency: 'PLN',
        changeDataLink: 'Zmień dane',
        nightsAt: (price: number, nights: number, label: string) => `${price} PLN × ${nights} ${label}`,
    },

    auth: {
        login: {
            eyebrow: 'Residenza Aurea',
            title: 'Zaloguj się',
            subtitle: 'Wróć do swoich rezerwacji.',
            emailLabel: 'Adres e-mail',
            emailPlaceholder: 'jan@example.com',
            passwordLabel: 'Hasło',
            passwordPlaceholder: '••••••••',
            submitIdle: 'Zaloguj się',
            submitBusy: 'Logowanie...',
            footerText: 'Nie masz konta? ',
            footerLink: 'Zarejestruj się',
            forgotPasswordLink: 'Zapomniałem hasła',
        },
        register: {
            eyebrow: 'Residenza Aurea',
            title: 'Utwórz konto',
            subtitle: 'Zarządzaj rezerwacjami w jednym miejscu.',
            fullNameLabel: 'Imię i nazwisko',
            fullNamePlaceholder: 'Jan Kowalski',
            emailLabel: 'Adres e-mail',
            emailPlaceholder: 'jan@example.com',
            phoneLabel: 'Numer telefonu',
            phonePlaceholder: '+48 600 000 000',
            passwordLabel: 'Hasło',
            passwordPlaceholder: 'Min. 8 znaków',
            confirmPasswordLabel: 'Powtórz hasło',
            confirmPasswordPlaceholder: 'Powtórz hasło',
            passwordMismatch: 'Hasła nie są identyczne.',
            submitIdle: 'Zarejestruj się',
            submitBusy: 'Rejestracja...',
            footerText: 'Masz już konto? ',
            footerLink: 'Zaloguj się',
        },
        forgotPassword: {
            eyebrow: 'Residenza Aurea',
            title: 'Zapomniałeś hasła?',
            subtitle: 'Podaj adres e-mail, a wyślemy Ci link do zresetowania hasła.',
            emailLabel: 'Adres e-mail',
            emailPlaceholder: 'jan@example.com',
            submitIdle: 'Wyślij link',
            submitBusy: 'Wysyłanie...',
            successMessage: 'Jeśli podany adres e-mail istnieje w naszej bazie, wysłaliśmy na niego link do zresetowania hasła.',
            footerText: 'Pamiętasz hasło? ',
            footerLink: 'Zaloguj się',
        },
        resetPassword: {
            eyebrow: 'Residenza Aurea',
            title: 'Ustaw nowe hasło',
            subtitle: 'Wpisz nowe hasło do swojego konta.',
            newPasswordLabel: 'Nowe hasło',
            newPasswordPlaceholder: 'Min. 8 znaków',
            confirmPasswordLabel: 'Powtórz hasło',
            confirmPasswordPlaceholder: 'Powtórz hasło',
            passwordMismatch: 'Hasła nie są identyczne.',
            submitIdle: 'Zresetuj hasło',
            submitBusy: 'Zapisywanie...',
            successMessage: 'Hasło zostało zmienione. Możesz się teraz zalogować.',
            missingTokenError: 'Brak tokena resetu hasła w linku. Poproś o nowy link resetu hasła.',
            footerText: 'Pamiętasz hasło? ',
            footerLink: 'Zaloguj się',
        },
        changePassword: {
            eyebrow: 'Twoje konto',
            title: 'Zmiana hasła',
            subtitle: 'Podaj aktualne hasło oraz nowe hasło, aby je zmienić.',
            currentPasswordLabel: 'Aktualne hasło',
            newPasswordLabel: 'Nowe hasło',
            confirmPasswordLabel: 'Powtórz nowe hasło',
            passwordMismatch: 'Hasła nie są identyczne.',
            submitIdle: 'Zmień hasło',
            submitBusy: 'Zapisywanie...',
        },
    },

    reservationDetails: {
        loading: 'Ładowanie rezerwacji...',
        notFound: 'Nie znaleziono rezerwacji.',
        reservationLabel: 'Rezerwacja',
        streetPrefix: 'ul. ',
        apartmentNumberPrefix: 'Apt. ',
        sectionStay: 'Pobyt',
        checkIn: 'Zameldowanie',
        checkOut: 'Wymeldowanie',
        nightsLabel: 'Liczba nocy',
        guestsLabel: 'Liczba gości',
        sectionGuest: 'Dane gościa',
        nameLabel: 'Imię i nazwisko',
        emailLabel: 'Adres e-mail',
        phoneLabel: 'Telefon',
        sectionBilling: 'Rozliczenie',
        rateLabel: 'Stawka',
        totalLabel: 'Łącznie',
        currency: 'PLN',
        payButtonIdle: 'Przejdź do płatności',
        payButtonBusy: 'Przekierowywanie...',
        paymentError: 'Nie udało się rozpocząć płatności. Spróbuj ponownie.',
        statusLabels: {
            PENDING_PAYMENT: 'Oczekuje na płatność',
            CONFIRMED: 'Potwierdzona',
            CANCELLED: 'Anulowana',
            COMPLETED: 'Zrealizowana'
        } as Record<string, string>
    },

    admin: {
        eyebrow: 'Administracja',
        title: 'Panel administratora',
        dataSection: 'Dane apartamentu',
        nameLabel: 'Nazwa apartamentu',
        descriptionLabel: 'Opis',
        streetLabel: 'Ulica',
        apartmentNumberLabel: 'Nr mieszkania',
        districtLabel: 'Dzielnica / Osiedle',
        cityLabel: 'Miasto',
        areaLabel: 'Metraż (m²)',
        floorLabel: 'Piętro',
        priceLabel: 'Cena za noc (PLN)',
        maxGuestsLabel: 'Maks. goście',
        saveIdle: 'Zapisz zmiany',
        saveBusy: 'Zapisywanie...',
        gallerySection: 'Galeria zdjęć',
        addPhoto: '+ Dodaj',
        uploading: 'Wysyłanie...',
        deletePhoto: 'Usuń',
        photoCountSuffix: ' zdjęć w galerii',
        accessSection: 'Kody dostępu',
        buildingEntranceCodeLabel: 'Kod do klatki',
        keyBoxCodeLabel: 'Kod do skrytki z kluczami',
        accessHint: 'Kody zostaną automatycznie wysłane gościowi mailem po potwierdzeniu płatności.',
    },

    myReservations: {
        eyebrow: 'Konto',
        title: 'Moje rezerwacje',
        loading: 'Ładowanie...',
        emptyText: 'Nie masz jeszcze żadnych rezerwacji.',
        emptyCta: 'Zarezerwuj teraz',
        checkIn: 'Zameldowanie',
        checkOut: 'Wymeldowanie',
        nights: 'Noce',
        guests: 'Goście',
        guestsNotProvided: '—',
        currency: 'PLN',
        detailsLink: 'Szczegóły →',
        newReservation: '+ Nowa rezerwacja',
    },

    account: {
        eyebrow: 'Twoje konto',
        title: 'Dane konta',
        fullNameLabel: 'Imię i nazwisko',
        emailLabel: 'Adres e-mail',
        phoneLabel: 'Numer telefonu',
        saveIdle: 'Zapisz zmiany',
        saveBusy: 'Zapisywanie...',
        saved: 'Dane zostały zaktualizowane.',
    },
} as const;