spring.application.name=apartmentbooking
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
app.frontend.url=${FRONTEND_URL:http://localhost:4200}
app.upload.dir=${UPLOAD_DIR:./uploads}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${MAX_FILE_SIZE:10MB}
app.reset-token.cooldown-minutes=${RESET_TOKEN_COOLDOWN_MINUTES:2}
app.reset-token.validity-hours=${RESET_TOKEN_VALIDITY_HOURS:1}
app.reservation.pending-payment-expiration-minutes=${RESERVATION_PENDING_PAYMENT_EXPIRATION_MINUTES:15}
app.backend.url=${BACKEND_URL:http://localhost:8080}


app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}
app.captcha.secret=${TURNSTILE_SECRET_KEY}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_LOGIN}
spring.mail.password=${BREVO_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_FROM_ADDRESS}
app.mail.from-name=${MAIL_FROM_NAME:Residenza Aurea}

app.payu.pos-id=${PAYU_POS_ID:300746}
app.payu.client-id=${PAYU_CLIENT_ID:300746}
app.payu.client-secret=${PAYU_CLIENT_SECRET:2ee86a66e5d97e3fadc400c9f19b065d}
app.payu.second-key=${PAYU_SECOND_KEY:b6ca15b0d1020e8094d9b5f8d163db54}
app.payu.base-url=${PAYU_BASE_URL:https://secure.snd.payu.com}